params:
  name: "RoPieee"
  contact: "hello@RoPieee.com"
  phone: "+31625068341"
  copyright: "© 2018 RoPieee. All rights reserved."
  description: "RoPieee"
  logourl: "images/logo.png"
  pricerange: "$$"
  keywords: ["RoPieee", "open source"]
  social:
    github: "RoPieee"
    facebook: "RoPieee"
    facebook_admin: "1111111"  # This needs to be a page admin to get domain insights
    twitter: "RoPieee"
    twitter_domain: "RoPieee.com" # This domain shows in twitter cards as "View on `twitter_domain`"
    googleplus: "RoPieee"
    pinterest: "RoPieee"
    instagram: "RoPieee"
    youtube: "RoPieee"
    linkedin: "RoPieee"
  authors:
    harry:
      name: "Harry ten Berge"
      gender: "Male"
      thumbnail: "harry.png"
      images: [
        ]
      bio: ""
      email: "harry@RoPieee.com"
      social:
         github: "spockfish"