baseURL = "http://www.ropieee.org/"
languageCode = "en-us"
title = "RoPieee"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3
googleAnalytics = "UA-98286335-1"
enableRobotsTXT = true

[params]
  favicon="favicon.ico"
  twitter = "https://twitter.com/Ro_Pieee"
