baseURL = "https://www.ropieee.org/"
title = "RoPieee"
theme = "ananke"

languageCode = "en-us"
languageLang = "en"
defaultContentLanguage = "en"

MetaDataFormat = "yaml"
SectionPagesMenu = "main"
Paginate = 3
googleAnalytics = "UA-98286335-1"
enableRobotsTXT = true

enableEmoji = true
copyright = "© 2018 RoPieee. All rights reserved."

[params]
  favicon="images/favicon-400x400.png"
  twitter = "https://twitter.com/Ro_Pieee"
