params:
  name: "RoPieee"
  contact: "htenberge+ropieee@gmail.com"
  phone: "+31625068341"
  copyright: "© 2018 RoPieee. All rights reserved."
  description: "RoPieee"
  logourl: "images/logo.png"
  imageurl: "images/logo.png"
  pricerange: "$$"
  primarylocation: "netherlands"
  keywords: ["RoPieee", "open source"]
  social:
    github: "RoPieee"
    twitter: "ro_pieee"
    twitter_domain: "RoPieee.org" # This domain shows in twitter cards as "View on `twitter_domain`"
